import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'hi';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        "migratrack": "MigraTrack",
        "dashboard": "Dashboard",
        "projects": "Projects",
        "users": "Users",
        "fields": "Fields",
        "modules": "Modules",
        "tables": "Tables",
        "databases": "Databases",
        "email": "Email",
        "overview": "Overview",
        "custom": "Custom",
        "issues": "Issues",
        "mode": "Mode",
        "logout": "Log Out",
        "settings": "Settings",
        "profile": "Profile",
        "administrator": "Administrator",
        "standard_user": "Standard User",
        "general_settings": "General Settings",
        "theme": "Theme",
        "language": "Language",
        "english": "English",
        "hindi": "Hindi",
        "select_theme": "Select Theme",
        "primary_color": "Primary Color",
        "gradient": "Gradient",
        "solid": "Solid",
        "save": "Save",
        "cancel": "Cancel",
        "dark_mode": "Dark Mode",
        "light_mode": "Light Mode",
        "search_placeholder": "Search...",
        "welcome": "Welcome",
        "total_projects": "Total Projects",
        "active_migrations": "Active Migrations",
        "pending_issues": "Pending Issues",
        "dashboard_overview": "Dashboard Overview",
        "dashboard_subtitle": "Real-time tracking of all active data migrations.",
        "completed_migrations": "Completed Migrations",
        "pending_transfers": "Pending Transfers",
        "project_status_distribution": "Project Status Distribution",
        "overall_migration_progress": "Overall Migration Progress",
        "migration_progress_by_client": "Migration Progress by Client",
        "recent_projects": "Recent Projects",
        "view_all_projects": "View All Projects",
        "no_active_projects": "No active projects yet.",
        "new_project": "New Project",
        "active": "Active",
        "completed": "Completed",
        "on_hold": "On Hold",
        "completed_checks": "Completed Checks",
        "pending_checks": "Pending Checks",
        "last_30_days": "Last 30 Days",
        "all_time": "All Time",
        "connection_error": "Connection Error",
        "retry": "Retry",
        "loading_dashboard": "Loading dashboard...",
        "create_new_project": "Create New Project",
        "description": "Description",
        "client_name": "Client Name",
        "project_manager": "Project Manager",
        "status": "Status",
        "actions": "Actions",
        "search_projects": "Search projects...",
        "data_transfer_checks": "Data Transfer Checks",
        "verification_list": "Verification List",
        "new_check": "New Check",
        "new_verification": "New Verification",
        "module_name": "Module Name",
        "sub_module": "Sub Module",
        "condition": "Condition",
        "source_table": "Source Table (Desktop)",
        "target_table": "Target Table (Web)",
        "desktop_count": "Desktop Count",
        "web_count": "Web Count",
        "difference": "Diff",
        "comments": "Comments",
        "save_as_new": "Save As New",
        "update_record": "Update Record",
        "edit": "Edit",
        "delete": "Delete",
        "correct": "Correct",
        "incorrect": "Incorrect",
        "pending": "Pending",
        "verified": "Verified",
        "sql_query": "SQL Query",
        "expected_result": "Expected Result",
        "actual_result": "Actual Result",
        "field_name": "Field Name",
        "search_records": "Search records...",
        "all_statuses": "All Statuses",
        "loading_data": "Loading data...",
        "confirm_delete": "Are you sure you want to delete this item?",
        "edit_check": "Edit Check",
        "add_new_check": "Add New Check",
        "edit_verification": "Edit Verification",
        "add_new_verification": "Add New Verification",
        "export_csv": "Export CSV",
        "no_records_found": "No records found.",
        "select_field": "Select Field",
        "description_optional": "Description (Optional)"
    },
    hi: {
        "migratrack": "मिग्राट्रैक",
        "dashboard": "डैशबोर्ड",
        "projects": "परियोजनाएं",
        "users": "उपयोगकर्ता",
        "fields": "फील्ड्स",
        "modules": "मॉड्यूल",
        "tables": "टेबल्स",
        "databases": "डेटाबेस",
        "email": "ईमेल",
        "overview": "अवलोकन",
        "custom": "कस्टम",
        "issues": "समस्याएं",
        "mode": "मोड",
        "logout": "लॉग आउट",
        "settings": "सेटिंग्स",
        "profile": "प्रोफाइल",
        "administrator": "प्रशासक",
        "standard_user": "मानक उपयोगकर्ता",
        "general_settings": "सामान्य सेटिंग्स",
        "theme": "थीम",
        "language": "भाषा",
        "english": "अंग्रेज़ी",
        "hindi": "हिंदी",
        "select_theme": "थीम चुनें",
        "primary_color": "प्राथमिक रंग",
        "gradient": "ग्रेडिएंट",
        "solid": "ठोस",
        "save": "सहेजें",
        "cancel": "रद्द करें",
        "dark_mode": "डार्क मोड",
        "light_mode": "लाइट मोड",
        "search_placeholder": "खोजें...",
        "welcome": "स्वागत है",
        "total_projects": "कुल परियोजनाएं",
        "active_migrations": "सक्रिय माइग्रेशन",
        "pending_issues": "लंबित समस्याएं",
        "dashboard_overview": "डैशबोर्ड अवलोकन",
        "dashboard_subtitle": "सभी सक्रिय डेटा माइग्रेशन की वास्तविक समय ट्रैकिंग।",
        "completed_migrations": "पूर्ण माइग्रेशन",
        "pending_transfers": "लंबित स्थानांतरण",
        "project_status_distribution": "परियोजना स्थिति वितरण",
        "overall_migration_progress": "कुल माइग्रेशन प्रगति",
        "migration_progress_by_client": "ग्राहक द्वारा माइग्रेशन प्रगति",
        "recent_projects": "हालिया परियोजनाएं",
        "view_all_projects": "सभी परियोजनाएं देखें",
        "no_active_projects": "अभी तक कोई सक्रिय परियोजना नहीं है।",
        "new_project": "नई परियोजना",
        "active": "सक्रिय",
        "completed": "पूर्ण",
        "on_hold": "होल्ड पर",
        "completed_checks": "पूर्ण चेक",
        "pending_checks": "लंबित चेक",
        "last_30_days": "लेटेस्ट 30 दिन",
        "all_time": "सभी समय",
        "connection_error": "कनेक्शन त्रुटि",
        "retry": "पुनः प्रयास करें",
        "loading_dashboard": "डैशबोर्ड लोड हो रहा है...",
        "create_new_project": "नई परियोजना बनाएं",
        "description": "विवरण",
        "client_name": "ग्राहक का नाम",
        "project_manager": "परियोजना प्रबंधक",
        "status": "स्थिति",
        "actions": "क्रियाएं",
        "search_projects": "परियोजनाएं खोजें...",
        "data_transfer_checks": "डेटा स्थानांतरण जाँच",
        "verification_list": "सत्यापन सूची",
        "new_check": "नई जाँच",
        "new_verification": "नया सत्यापन",
        "module_name": "मॉड्यूल का नाम",
        "sub_module": "सब-मॉड्यूल",
        "condition": "शर्त",
        "source_table": "स्रोत तालिका (डेस्कटॉप)",
        "target_table": "लक्ष्य तालिका (वेब)",
        "desktop_count": "डेस्कटॉप गणना",
        "web_count": "वेब गणना",
        "difference": "अंतर",
        "comments": "टिप्पणियाँ",
        "save_as_new": "नए के रूप में सहेजें",
        "update_record": "रिकॉर्ड अपडेट करें",
        "edit": "संपादित करें",
        "delete": "हटाएं",
        "correct": "सही",
        "incorrect": "गलत",
        "pending": "लंबित",
        "verified": "सत्यापित",
        "sql_query": "SQL क्वेरी",
        "expected_result": "अपेक्षित परिणाम",
        "actual_result": "वास्तविक परिणाम",
        "field_name": "फ़ील्ड का नाम",
        "search_records": "रिकॉर्ड खोजें...",
        "all_statuses": "सभी स्थितियां",
        "loading_data": "डेटा लोड हो रहा है...",
        "confirm_delete": "क्या आप वाकई इस आइटम को हटाना चाहते हैं?",
        "edit_check": "जाँच संपादित करें",
        "add_new_check": "नई जाँच जोड़ें",
        "edit_verification": "सत्यापन संपादित करें",
        "add_new_verification": "नया सत्यापन जोड़ें",
        "export_csv": "CSV निर्यात करें",
        "no_records_found": "कोई रिकॉर्ड नहीं मिला।",
        "select_field": "फ़ील्ड चुनें",
        "description_optional": "विवरण (वैकल्पिक)"
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>(() => {
        return (localStorage.getItem('language') as Language) || 'en';
    });

    useEffect(() => {
        localStorage.setItem('language', language);
    }, [language]);

    const t = (key: string): string => {
        const lowerKey = key.toLowerCase().replace(/ /g, '_');
        return translations[language][lowerKey] || translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error("useLanguage must be used within a LanguageProvider");
    return context;
};
